import { env } from '../../modules/env'

export const MIN_NAME_SIZE = 2
export const MAX_NAME_SIZE = 15
export const VOTING_POWER_TO_PASS_LINKED_WEARABLES =
  process.env.GATSBY_VOTING_POWER_TO_PASS_LINKED_WEARABLES || env('GATSBY_VOTING_POWER_TO_PASS_LINKED_WEARABLES')
export const VOTING_POWER_TO_PASS_CATALYST =
  process.env.VOTING_POWER_TO_PASS_CATALYST || env('GATSBY_VOTING_POWER_TO_PASS_CATALYST')
export const VOTING_POWER_TO_PASS_BAN_NAME =
  process.env.VOTING_POWER_TO_PASS_BAN_NAME || env('GATSBY_VOTING_POWER_TO_PASS_BAN_NAME')
export const VOTING_POWER_TO_PASS_POI = process.env.VOTING_POWER_TO_PASS_POI || env('GATSBY_VOTING_POWER_TO_PASS_POI')
export const VOTING_POWER_TO_PASS_POLL =
  process.env.VOTING_POWER_TO_PASS_POLL || env('GATSBY_VOTING_POWER_TO_PASS_POLL')
export const VOTING_POWER_TO_PASS_DRAFT =
  process.env.VOTING_POWER_TO_PASS_DRAFT || env('GATSBY_VOTING_POWER_TO_PASS_DRAFT')
export const VOTING_POWER_TO_PASS_GOVERNANCE =
  process.env.GATSBY_VOTING_POWER_TO_PASS_GOVERNANCE || env('GATSBY_VOTING_POWER_TO_PASS_GOVERNANCE')
export const SUBMISSION_THRESHOLD_DRAFT =
  process.env.SUBMISSION_THRESHOLD_DRAFT || env('GATSBY_SUBMISSION_THRESHOLD_DRAFT')
export const SUBMISSION_THRESHOLD_GOVERNANCE =
  process.env.SUBMISSION_THRESHOLD_GOVERNANCE || env('GATSBY_SUBMISSION_THRESHOLD_GOVERNANCE')
export const SUBMISSION_THRESHOLD_POLL =
  process.env.SUBMISSION_THRESHOLD_POLL || env('GATSBY_SUBMISSION_THRESHOLD_POLL')
