import { clientEnv } from '../../utils/clientEnv'

export const MIN_NAME_SIZE = 2
export const MAX_NAME_SIZE = 15
export const VOTING_POWER_TO_PASS_LINKED_WEARABLES =
  process.env.GATSBY_VOTING_POWER_TO_PASS_LINKED_WEARABLES || clientEnv('GATSBY_VOTING_POWER_TO_PASS_LINKED_WEARABLES')
export const VOTING_POWER_TO_PASS_CATALYST =
  process.env.VOTING_POWER_TO_PASS_CATALYST || clientEnv('GATSBY_VOTING_POWER_TO_PASS_CATALYST')
export const VOTING_POWER_TO_PASS_BAN_NAME =
  process.env.VOTING_POWER_TO_PASS_BAN_NAME || clientEnv('GATSBY_VOTING_POWER_TO_PASS_BAN_NAME')
export const VOTING_POWER_TO_PASS_POI =
  process.env.VOTING_POWER_TO_PASS_POI || clientEnv('GATSBY_VOTING_POWER_TO_PASS_POI')
export const VOTING_POWER_TO_PASS_POLL =
  process.env.GATSBY_VOTING_POWER_TO_PASS_POLL || clientEnv('GATSBY_VOTING_POWER_TO_PASS_POLL')
export const VOTING_POWER_TO_PASS_DRAFT =
  process.env.GATSBY_VOTING_POWER_TO_PASS_DRAFT || clientEnv('GATSBY_VOTING_POWER_TO_PASS_DRAFT')
export const VOTING_POWER_TO_PASS_GOVERNANCE =
  process.env.GATSBY_VOTING_POWER_TO_PASS_GOVERNANCE || clientEnv('GATSBY_VOTING_POWER_TO_PASS_GOVERNANCE')
export const VOTING_POWER_TO_PASS_PITCH =
  process.env.GATSBY_VOTING_POWER_TO_PASS_PITCH || clientEnv('GATSBY_VOTING_POWER_TO_PASS_PITCH')
export const VOTING_POWER_TO_PASS_TENDER =
  process.env.GATSBY_VOTING_POWER_TO_PASS_TENDER || clientEnv('GATSBY_VOTING_POWER_TO_PASS_TENDER')
export const VOTING_POWER_TO_PASS_BID =
  process.env.GATSBY_VOTING_POWER_TO_PASS_BID || clientEnv('GATSBY_VOTING_POWER_TO_PASS_BID')
export const SUBMISSION_THRESHOLD_DRAFT =
  process.env.GATSBY_SUBMISSION_THRESHOLD_DRAFT || clientEnv('GATSBY_SUBMISSION_THRESHOLD_DRAFT')
export const SUBMISSION_THRESHOLD_GOVERNANCE =
  process.env.GATSBY_SUBMISSION_THRESHOLD_GOVERNANCE || clientEnv('GATSBY_SUBMISSION_THRESHOLD_GOVERNANCE')
export const SUBMISSION_THRESHOLD_POLL =
  process.env.GATSBY_SUBMISSION_THRESHOLD_POLL || clientEnv('GATSBY_SUBMISSION_THRESHOLD_POLL')
export const SUBMISSION_THRESHOLD_PITCH =
  process.env.GATSBY_SUBMISSION_THRESHOLD_PITCH || clientEnv('GATSBY_SUBMISSION_THRESHOLD_PITCH')
export const SUBMISSION_THRESHOLD_TENDER =
  process.env.GATSBY_SUBMISSION_THRESHOLD_TENDER || clientEnv('GATSBY_SUBMISSION_THRESHOLD_TENDER')
export const SUBMISSION_THRESHOLD_HIRING =
  process.env.GATSBY_SUBMISSION_THRESHOLD_HIRING || clientEnv('GATSBY_SUBMISSION_THRESHOLD_HIRING')
export const SUBMISSION_THRESHOLD_GRANT =
  process.env.GATSBY_SUBMISSION_THRESHOLD_GRANT || clientEnv('GATSBY_SUBMISSION_THRESHOLD_GRANT')
export const VOTING_POWER_TO_PASS_HIRING =
  process.env.GATSBY_VOTING_POWER_TO_PASS_HIRING || clientEnv('GATSBY_VOTING_POWER_TO_PASS_HIRING')
