export const SNAPSHOT_PRIVATE_KEY = process.env.SNAPSHOT_PRIVATE_KEY || ''
export const SNAPSHOT_API_KEY = process.env.SNAPSHOT_API_KEY || ''
export const GATSBY_SNAPSHOT_API = process.env.GATSBY_SNAPSHOT_API || ''
export const OTTERSPACE_QUERY_ENDPOINT = process.env.OTTERSPACE_QUERY_ENDPOINT || ''
export const OTTERSPACE_DAO_RAFT_ID = process.env.OTTERSPACE_DAO_RAFT_ID || ''
export const SNAPSHOT_SPACE = process.env.GATSBY_SNAPSHOT_SPACE || ''
export const SNAPSHOT_ADDRESS = process.env.GATSBY_SNAPSHOT_ADDRESS || ''
export const SNAPSHOT_DURATION = Number(process.env.GATSBY_SNAPSHOT_DURATION || '')
export const SNAPSHOT_URL = process.env.GATSBY_SNAPSHOT_URL || 'https://testnet.snapshot.org/'
export const SNAPSHOT_QUERY_ENDPOINT = `https://gateway-arbitrum.network.thegraph.com/api/${process.env.THE_GRAPH_API_KEY}/subgraphs/id/4YgtogVaqoM8CErHWDK8mKQ825BcVdKB8vBYmb4avAQo`
export const SNAPSHOT_API = process.env.GATSBY_SNAPSHOT_API || ''
export const VESTINGS_QUERY_ENDPOINT = `https://gateway-arbitrum.network.thegraph.com/api/${process.env.THE_GRAPH_API_KEY}/subgraphs/id/Dek4AeCYyGQ8Y2yeVNb2N7cfQDy7Pinka1jD5uWvRCxG`
