export enum ErrorCategory {
  Badges = 'Badges',
  Bid = 'Bid',
  Budget = 'Budget',
  Discourse = 'Discourse',
  Events = 'Events',
  Job = 'Job',
  Profile = 'Profile',
  Proposal = 'Proposal',
  Snapshot = 'Snapshot',
  Transparency = 'Transparency',
  Vesting = 'Vesting',
  Voting = 'Voting',
  Discord = 'Discord',
  Newsletter = 'Newsletter',
  Notifications = 'Notifications',
}
