import { DiscoursePostInTopic } from '../../../api/Discourse'

export const ONE_USER_POST = [
  {
    id: 184,
    name: 'dao',
    username: 'dao',
    avatar_template:
      'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
    created_at: '2021-11-09T19:32:19.208Z',
    cooked:
      '<blockquote>\n<p>by 0xcd15d83f42179b9a5b515eea0975f554444a9646</p>\n</blockquote>\n<h2>\n<a name="piccadilly-1" class="anchor" href="#piccadilly-1"></a>PICCADILLY</h2>\n<p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/72ec6244205fd479df8e104b62da54ca2dc6254d.png" data-download-href="/uploads/short-url/goESFfqmThwxCBzsdKjwRgKZmQB.png?dl=1" title="PICCADILLY"><img src="https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/72ec6244205fd479df8e104b62da54ca2dc6254d.png" alt="PICCADILLY" data-base62-sha1="goESFfqmThwxCBzsdKjwRgKZmQB" width="500" height="500" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/optimized/1X/72ec6244205fd479df8e104b62da54ca2dc6254d_2_10x10.png"><div class="meta">\n<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">PICCADILLY</span><span class="informations">1024×1024 3.92 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>\n</div></a></div></p>\n<p>Should the scene located at -45,14 be added to the Point of Interest list?</p>\n<h2>\n<a name="description-2" class="anchor" href="#description-2"></a>Description</h2>\n<p>Why do you think that this location should be a featured point of interest within Decentraland? Please describe the scene located at these coordinates, explaining how it would be interesting or helpful for other Decentraland users.</p>\n<p><strong><a href="https://localhost:8000/proposal/?id=acae3a20-4193-11ec-bcd4-47b9e719adfc">Vote on this proposal on the Decentraland DAO</a></strong></p>\n<p><strong><a href="https://snapshot.org/#/frami.eth/proposal/QmPtv4vhWNiUEHHaVc7BxXxcZLpmcXcprKNGwFnZAJrQzR">View this proposal on Snapshot</a></strong></p>',
    post_number: 1,
    post_type: 1,
    updated_at: '2021-11-09T19:37:25.695Z',
    reply_count: 1,
    reply_to_post_number: null,
    quote_count: 0,
    incoming_link_count: 1,
    reads: 2,
    readers_count: 1,
    score: 0.2,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'dao',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 2,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    link_counts: [
      {
        url: 'https://localhost:8000/proposal/?id=acae3a20-4193-11ec-bcd4-47b9e719adfc',
        internal: false,
        reflection: false,
        clicks: 0,
      },
      {
        url: 'https://snapshot.org/#/frami.eth/proposal/QmPtv4vhWNiUEHHaVc7BxXxcZLpmcXcprKNGwFnZAJrQzR',
        internal: false,
        reflection: false,
        title: 'Snapshot',
        clicks: 0,
      },
      {
        url: 'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/72ec6244205fd479df8e104b62da54ca2dc6254d.png',
        internal: false,
        reflection: false,
        title: '72ec6244205fd479df8e104b62da54ca2dc6254d.png',
        clicks: 0,
      },
    ],
    read: false,
    user_title: null,
    bookmarked: false,
    actions_summary: [
      {
        id: 2,
        can_act: true,
      },
      {
        id: 3,
        can_act: true,
      },
      {
        id: 4,
        can_act: true,
      },
      {
        id: 8,
        can_act: true,
      },
      {
        id: 7,
        can_act: true,
      },
    ],
    moderator: true,
    admin: true,
    staff: true,
    user_id: -1,
    hidden: false,
    trust_level: 4,
    deleted_at: null,
    user_deleted: false,
    edit_reason: 'downloaded local copies of images',
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:15:40.095Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
  {
    id: 185,
    name: 'dao',
    username: 'dao',
    avatar_template:
      'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
    created_at: '2021-11-09T19:31:00.477Z',
    cooked:
      '<p>Add the location -45,14 to the Points of Interest</p>\n<p>This proposal is now in status: PASSED.</p>\n<p>Voting Results:</p>\n<ul>\n<li>Yes 100% 500 VP (1 votes)</li>\n<li>No 0% 0 VP (0 votes)</li>\n</ul>',
    post_number: 2,
    post_type: 1,
    updated_at: '2021-11-09T19:42:03.068Z',
    reply_count: 0,
    reply_to_post_number: null,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 2,
    readers_count: 1,
    score: 0.2,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'dao',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    bookmarked: false,
    actions_summary: [
      {
        id: 2,
        can_act: true,
      },
      {
        id: 3,
        can_act: true,
      },
      {
        id: 4,
        can_act: true,
      },
      {
        id: 8,
        can_act: true,
      },
      {
        id: 7,
        can_act: true,
      },
    ],
    moderator: true,
    admin: true,
    staff: true,
    user_id: -1,
    hidden: false,
    trust_level: 4,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:15:40.095Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
  {
    id: 217,
    name: 'Yemel Jardi',
    username: 'yemel',
    avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
    created_at: '2021-11-19T21:36:13.181Z',
    cooked: '<p>I am commenting as Yemel</p>',
    post_number: 3,
    post_type: 1,
    updated_at: '2021-11-19T21:36:13.181Z',
    reply_count: 0,
    reply_to_post_number: 1,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 1,
    readers_count: 0,
    score: 0,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'Yemel Jardi',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    reply_to_user: {
      username: 'dao',
      avatar_template:
        'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
    },
    bookmarked: false,
    actions_summary: [
      {
        id: 2,
        can_act: true,
      },
      {
        id: 3,
        can_act: true,
      },
      {
        id: 4,
        can_act: true,
      },
      {
        id: 8,
        can_act: true,
      },
      {
        id: 6,
        can_act: true,
      },
      {
        id: 7,
        can_act: true,
      },
    ],
    moderator: false,
    admin: true,
    staff: true,
    user_id: 1,
    hidden: false,
    trust_level: 4,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:18:07.188Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
]
export const SEVERAL_USERS_POST = [
  {
    id: 217,
    name: 'Yemel Jardi',
    username: 'yemel',
    avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
    created_at: '2021-11-19T21:36:13.181Z',
    cooked: '<p>I am commenting as Yemel</p>',
    post_number: 3,
    post_type: 1,
    updated_at: '2021-11-19T21:36:13.181Z',
    reply_count: 1,
    reply_to_post_number: 1,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 3,
    readers_count: 2,
    score: 5.6,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'Yemel Jardi',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    reply_to_user: {
      username: 'system',
      avatar_template:
        'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
    },
    bookmarked: false,
    actions_summary: [],
    moderator: false,
    admin: true,
    staff: true,
    user_id: 1,
    hidden: false,
    trust_level: 4,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:18:07.188Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
  {
    id: 218,
    name: 'Yemel Jardi',
    username: 'yemel',
    avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
    created_at: '2021-11-20T06:23:47.340Z',
    cooked:
      '<p><img src="https://emoji.discourse-cdn.com/twitter/stuck_out_tongue.png?v=10" title=":stuck_out_tongue:" class="emoji only-emoji" alt=":stuck_out_tongue:"></p>\n' +
      '<pre><code class="lang-auto">type or paste code here\n' +
      '</code></pre>\n' +
      '<h1> header! </h1>\n' +
      'this is simple text\n' +
      '<h3>such a nice comment!</h3>',
    post_number: 4,
    post_type: 1,
    updated_at: '2021-11-20T06:23:47.340Z',
    reply_count: 1,
    reply_to_post_number: 3,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 3,
    readers_count: 2,
    score: 5.6,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'Yemel Jardi',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    reply_to_user: {
      username: 'yemel',
      avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
    },
    bookmarked: false,
    actions_summary: [],
    moderator: false,
    admin: true,
    staff: true,
    user_id: 1,
    hidden: false,
    trust_level: 4,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:18:07.188Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
  {
    id: 232,
    name: 'noavatar',
    username: 'noavatar',
    avatar_template: 'https://avatars.discourse-cdn.com/v4/letter/n/b782af/{size}.png',
    created_at: '2021-11-24T13:38:18.607Z',
    cooked:
      '<p>this is a super normal comment from someone with no avatar. How does it look? Something something long text long text.</p>',
    post_number: 6,
    post_type: 1,
    updated_at: '2021-11-24T13:38:18.607Z',
    reply_count: 0,
    reply_to_post_number: null,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 1,
    readers_count: 0,
    score: 0.2,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'noavatar',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    bookmarked: false,
    actions_summary: [],
    moderator: false,
    admin: false,
    staff: false,
    user_id: 5,
    hidden: false,
    trust_level: 1,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-11-24T13:36:32.838Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
  {
    id: 219,
    name: 'lemu',
    username: 'lemu',
    avatar_template: '/user_avatar/forum.decentraland.vote/lemu/{size}/5_2.png',
    created_at: '2021-11-20T06:35:09.181Z',
    cooked:
      '<p>nice comment bro!!! <img src="https://emoji.discourse-cdn.com/twitter/heart_eyes.png?v=10" title=":heart_eyes:" class="emoji" alt=":heart_eyes:"></p>',
    post_number: 5,
    post_type: 1,
    updated_at: '2021-11-20T06:35:49.946Z',
    reply_count: 0,
    reply_to_post_number: 4,
    quote_count: 0,
    incoming_link_count: 0,
    reads: 2,
    readers_count: 1,
    score: 0.4,
    yours: false,
    topic_id: 70,
    topic_slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    display_username: 'lemu',
    primary_group_name: null,
    flair_name: null,
    flair_url: null,
    flair_bg_color: null,
    flair_color: null,
    version: 1,
    can_edit: false,
    can_delete: false,
    can_recover: false,
    can_wiki: false,
    read: false,
    user_title: null,
    reply_to_user: {
      username: 'yemel',
      avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
    },
    bookmarked: false,
    actions_summary: [],
    moderator: false,
    admin: false,
    staff: false,
    user_id: 2,
    hidden: false,
    trust_level: 1,
    deleted_at: null,
    user_deleted: false,
    edit_reason: null,
    can_view_edit_history: true,
    wiki: false,
    user_created_at: '2021-10-26T14:38:24.928Z',
    user_date_of_birth: null,
    can_accept_answer: false,
    can_unaccept_answer: false,
    accepted_answer: false,
  },
]

export function createWithPosts(posts: DiscoursePostInTopic[]) {
  return {
    post_stream: {
      posts: posts,
      stream: [184, 185, 217],
    },
    timeline_lookup: [
      [1, 10],
      [3, 0],
    ],
    suggested_topics: [
      {
        id: 19,
        title: '[DAO: QmNNF7J] G1',
        fancy_title: '[DAO: QmNNF7J] G1',
        slug: 'dao-qmnnf7j-g1',
        posts_count: 1,
        reply_count: 0,
        highest_post_number: 1,
        image_url: null,
        created_at: '2021-10-27T01:52:59.448Z',
        last_posted_at: '2021-10-27T01:52:59.527Z',
        bumped: true,
        bumped_at: '2021-10-27T01:52:59.527Z',
        archetype: 'regular',
        unseen: false,
        pinned: false,
        unpinned: null,
        visible: true,
        closed: false,
        archived: false,
        bookmarked: null,
        liked: null,
        tags: [],
        like_count: 0,
        views: 0,
        category_id: 5,
        featured_link: null,
        has_accepted_answer: false,
        posters: [
          {
            extras: 'latest single',
            description: 'Original Poster, Most Recent Poster',
            user: {
              id: -1,
              username: 'dao',
              name: 'dao',
              avatar_template:
                'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
            },
          },
        ],
      },
      {
        id: 38,
        title: '[DAO: QmYZuFb] pollposal',
        fancy_title: '[DAO: QmYZuFb] pollposal',
        slug: 'dao-qmyzufb-pollposal',
        posts_count: 4,
        reply_count: 0,
        highest_post_number: 4,
        image_url: null,
        created_at: '2021-11-01T15:47:08.547Z',
        last_posted_at: '2021-11-01T15:47:00.438Z',
        bumped: false,
        bumped_at: '2021-11-01T15:47:00.438Z',
        archetype: 'regular',
        unseen: false,
        pinned: false,
        unpinned: null,
        visible: true,
        closed: false,
        archived: false,
        bookmarked: null,
        liked: null,
        tags: [],
        like_count: 0,
        views: 1,
        category_id: 5,
        featured_link: null,
        has_accepted_answer: false,
        posters: [
          {
            extras: 'latest single',
            description: 'Original Poster, Most Recent Poster',
            user: {
              id: -1,
              username: 'dao',
              name: 'dao',
              avatar_template:
                'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
            },
          },
        ],
      },
      {
        id: 43,
        title: '[DAO: QmQJK4X] poll 11 no votes',
        fancy_title: '[DAO: QmQJK4X] poll 11 no votes',
        slug: 'dao-qmqjk4x-poll-11-no-votes',
        posts_count: 3,
        reply_count: 0,
        highest_post_number: 3,
        image_url: null,
        created_at: '2021-11-02T15:09:07.942Z',
        last_posted_at: '2021-11-02T15:08:00.346Z',
        bumped: false,
        bumped_at: '2021-11-02T15:08:00.346Z',
        archetype: 'regular',
        unseen: false,
        pinned: false,
        unpinned: null,
        visible: true,
        closed: false,
        archived: false,
        bookmarked: null,
        liked: null,
        tags: [],
        like_count: 0,
        views: 1,
        category_id: 5,
        featured_link: null,
        has_accepted_answer: false,
        posters: [
          {
            extras: 'latest single',
            description: 'Original Poster, Most Recent Poster',
            user: {
              id: -1,
              username: 'dao',
              name: 'dao',
              avatar_template:
                'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
            },
          },
        ],
      },
      {
        id: 45,
        title: '[DAO: QmUy9bA] Add the location -54,14 to the Points of Interest',
        fancy_title: '[DAO: QmUy9bA] Add the location -54,14 to the Points of Interest',
        slug: 'dao-qmuy9ba-add-the-location-54-14-to-the-points-of-interest',
        posts_count: 9,
        reply_count: 0,
        highest_post_number: 9,
        image_url:
          'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/9829946f4791911da622b6d5590f8a8085b086c2.png',
        created_at: '2021-11-02T16:59:00.255Z',
        last_posted_at: '2021-11-02T16:58:00.241Z',
        bumped: false,
        bumped_at: '2021-11-02T16:58:00.241Z',
        archetype: 'regular',
        unseen: false,
        pinned: false,
        unpinned: null,
        visible: true,
        closed: false,
        archived: false,
        bookmarked: null,
        liked: null,
        tags: [],
        like_count: 0,
        views: 0,
        category_id: 5,
        featured_link: null,
        has_accepted_answer: false,
        posters: [
          {
            extras: 'latest single',
            description: 'Original Poster, Most Recent Poster',
            user: {
              id: -1,
              username: 'dao',
              name: 'dao',
              avatar_template:
                'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
            },
          },
        ],
      },
      {
        id: 17,
        title: '[DAO: QmSycdb] Testing grant proposal 2',
        fancy_title: '[DAO: QmSycdb] Testing grant proposal 2',
        slug: 'dao-qmsycdb-testing-grant-proposal-2',
        posts_count: 3,
        reply_count: 0,
        highest_post_number: 3,
        image_url: null,
        created_at: '2021-10-26T22:03:01.606Z',
        last_posted_at: '2021-10-26T22:59:34.329Z',
        bumped: true,
        bumped_at: '2021-10-26T22:59:34.329Z',
        archetype: 'regular',
        unseen: false,
        pinned: false,
        unpinned: null,
        visible: true,
        closed: false,
        archived: false,
        bookmarked: null,
        liked: null,
        tags: [],
        like_count: 0,
        views: 2,
        category_id: 5,
        featured_link: null,
        has_accepted_answer: false,
        posters: [
          {
            extras: null,
            description: 'Original Poster',
            user: {
              id: -1,
              username: 'dao',
              name: 'dao',
              avatar_template:
                'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
            },
          },
          {
            extras: 'latest',
            description: 'Most Recent Poster',
            user: {
              id: 1,
              username: 'yemel',
              name: 'Yemel Jardi',
              avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
            },
          },
        ],
      },
    ],
    tags: [],
    id: 70,
    title: '[DAO: QmPtv4v] Add the location -45,14 to the Points of Interest',
    fancy_title: '[DAO: QmPtv4v] Add the location -45,14 to the Points of Interest',
    posts_count: 3,
    created_at: '2021-11-09T19:32:19.131Z',
    views: 2,
    reply_count: 1,
    like_count: 0,
    last_posted_at: '2021-11-19T21:36:13.181Z',
    visible: true,
    closed: false,
    archived: false,
    has_summary: false,
    archetype: 'regular',
    slug: 'dao-qmptv4v-add-the-location-45-14-to-the-points-of-interest',
    category_id: 5,
    word_count: 125,
    deleted_at: null,
    user_id: -1,
    featured_link: null,
    pinned_globally: false,
    pinned_at: null,
    pinned_until: null,
    image_url:
      'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/72ec6244205fd479df8e104b62da54ca2dc6254d.png',
    slow_mode_seconds: 0,
    draft: null,
    draft_key: 'topic_70',
    draft_sequence: 0,
    unpinned: null,
    pinned: false,
    current_post_number: 1,
    highest_post_number: 3,
    deleted_by: null,
    actions_summary: [
      {
        id: 4,
        count: 0,
        hidden: false,
        can_act: true,
      },
      {
        id: 8,
        count: 0,
        hidden: false,
        can_act: true,
      },
      {
        id: 7,
        count: 0,
        hidden: false,
        can_act: true,
      },
    ],
    chunk_size: 20,
    bookmarked: false,
    bookmarks: [],
    topic_timer: null,
    message_bus_last_id: 2,
    participant_count: 2,
    show_read_indicator: false,
    thumbnails: [
      {
        max_width: null,
        max_height: null,
        width: 1024,
        height: 1024,
        url: 'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/72ec6244205fd479df8e104b62da54ca2dc6254d.png',
      },
    ],
    slow_mode_enabled_until: null,
    tags_disable_ads: false,
    details: {
      can_edit: false,
      notification_level: 1,
      can_invite_to: true,
      can_create_post: true,
      can_reply_as_new_topic: true,
      can_flag_topic: true,
      participants: [
        {
          id: -1,
          username: 'dao',
          name: 'dao',
          avatar_template: '/user_avatar/forum.decentraland.vote/dao/{size}/3_2.png',
          post_count: 2,
          primary_group_name: null,
          flair_name: null,
          flair_url: null,
          flair_color: null,
          flair_bg_color: null,
          admin: true,
          moderator: true,
          trust_level: 4,
        },
        {
          id: 1,
          username: 'yemel',
          name: 'Yemel Jardi',
          avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
          post_count: 1,
          primary_group_name: null,
          flair_name: null,
          flair_url: null,
          flair_color: null,
          flair_bg_color: null,
          admin: true,
          trust_level: 4,
        },
      ],
      created_by: {
        id: -1,
        username: 'dao',
        name: 'dao',
        avatar_template:
          'https://aws1.discourse-cdn.com/standard10/uploads/decentraland1/original/1X/3d6235c1e9ab1b391e30a2e10ed7c32c286e329e.png',
      },
      last_poster: {
        id: 1,
        username: 'yemel',
        name: 'Yemel Jardi',
        avatar_template: '/user_avatar/forum.decentraland.vote/yemel/{size}/1_2.png',
      },
    },
  }
}
