export const MESSAGE_TIMEOUT_TIME = 5 * 60 * 1000 // 5mins
export const GATSBY_DISCOURSE_CONNECT_THREAD = process.env.GATSBY_DISCOURSE_CONNECT_THREAD
export const GATSBY_DISCORD_PROFILE_VERIFICATION_URL = process.env.GATSBY_DISCORD_PROFILE_VERIFICATION_URL
