name: Assign Reviewers

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:

  assign:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: assign_pr
        with:
          route: POST /repos/:repository/pulls/:pull_number/requested_reviewers
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          reviewers: '[ "2fd" ]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}