name: Master build

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      registry-path: ${{ steps.push-to-quay.outputs.registry-path }}
      registry-paths: ${{ steps.push-to-quay.outputs.registry-paths }}
    steps:
      - uses: actions/checkout@v4

      - name: node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: set up git
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: installing
        run: npm ci

      - name: build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: governance
          tags: ${{ github.sha }} latest
          dockerfiles: |
            ./Dockerfile
          build-args: |
            version_number=${{ github.sha }}

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  deployment:
    needs: [build-push]
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "${{ needs.build-push.outputs.registry-path }}"
          serviceName: governance2
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}
