name: Next pull request build

on:
  pull_request:
    branches:
      - next
    types:
      - opened
      - synchronize

jobs:
  build:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: governance
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
